maxplanck-ie/snakepipes

shared/rules/deepTools_ChIP.snakefile

scaleTo1x for ratio=subtract, not for ratio=log2

be more precise on bamCompare with scaleFactorsMethod and only use

---

shared/tools/CSAW.R
shared/tools/DB_functions.R
shared/tools/DE_functions.R
shared/tools/install_R_packages.txt

Chipseq revamp

---

shared/common_functions.py
shared/tools/sample_qc_report_PE.py
shared/tools/sample_qc_report_SE.py
workflows/ATAC-seq/ATAC-seq
workflows/ChIP-seq/ChIP-seq
workflows/scRNAseq/scRNAseq-mapcount

python in current default snakemake 4.2.0
closes #62

fix: hardcode snakemake version to 3.12 in all wrappers to avoid missing

---

shared/common_functions.py
shared/rules/ChIP_qc_report.snakefile
shared/tools/sample_qc_report_PE.py
shared/tools/sample_qc_report_SE.py

as well as the script is called in the rule qc_report_sample (ChIP_qc_report.snakefile), fix pep8 along

Fix python3 compatibillity of sample_qc_report_{SE,PE}.py

---

shared/tools/sample_qc_report_PE.py
shared/tools/sample_qc_report_SE.py

* fix: we also need to convert the result of map to a list
* now we also need to test if variable exists
* fix again, now also in sample_qc_report_SE.py
* fix pep8

Fix python3 again (#68)

---

shared/paths.yaml
shared/rules/TrimGalore.snakefile

This partially fixes #76 by updating cutadapt to use multiple threads (8). I can add picard too if people let me know the version they'd like and how many threads they'd like the various programs to use (I don't use picard much, it's too slow).

Fix76 faster cutadapt

---

shared/rules/DESeq2.snakefile
workflows/RNA-seq/RNA-seq
workflows/RNA-seq/Snakefile

the newly implemented cluster_config is working

---

README.rst
shared/cluster.yaml
shared/rules/RNA_mapping.snakefile
shared/rules/bam_filtering.snakefile
shared/rules/deepTools_RNA.snakefile
shared/rules/sambamba.snakefile
workflows/RNA-seq/RNA-seq
workflows/RNA-seq/Snakefile
workflows/RNA-seq/cluster.yaml
workflows/RNA-seq/cluster.yml

on sambamba and cluster.yml (bring back)

new changes

---

shared/cluster.yaml
workflows/ATAC-seq/ATAC-seq
workflows/ATAC-seq/defaults.yaml
workflows/ChIP-seq/ChIP-seq
workflows/ChIP-seq/defaults.yaml
workflows/DNA-mapping/DNA-mapping
workflows/DNA-mapping/defaults.yaml
workflows/HiC/HiC
workflows/HiC/defaults.yaml
workflows/RNA-seq/RNA-seq
workflows/RNA-seq/Snakefile
workflows/scRNAseq/defaults.yaml
workflows/scRNAseq/scRNAseq-mapcount

Generic cluster usage cleanups

---

shared/rules/bam_filtering.snakefile
workflows/DNA-mapping/DNA-mapping
workflows/DNA-mapping/internals.snakefile

This should finish fixing bam_filtering

Update the filtering in the main python script to prevent race conditions

---

shared/cluster.yaml
shared/rules/SNPsplit.snakefile
shared/rules/deepTools_qc_allelic.snakefile
shared/rules/envs/shared_environment.yaml

Allele specific + others

---

shared/rules/deepTools_RNA_allelic.snakefile
shared/rules/filter_annotation.snakefile
workflows/RNA-seq/RNA-seq
workflows/RNA-seq/Snakefile
workflows/WGBS/WGBS

fix use all wildcards in allelic rule
fix use wdir instead of outdir in WGBS DAG option

fix RNA-seq snakefile includes and some other things

---

workflows/RNA-seq/RNA-seq

remove comment

---

workflows/ATAC-seq/ATAC-seq
workflows/ChIP-seq/ChIP-seq
workflows/DNA-mapping/DNA-mapping
workflows/HiC/HiC
workflows/RNA-seq/RNA-seq
workflows/WGBS/WGBS
workflows/scRNAseq/scRNAseq-mapcount

Verbose DAG

---

snakePipes/shared/defaults.yaml
snakePipes/shared/rules/DESeq2.snakefile
snakePipes/shared/tools/snakediff/R/DE_functions.R

fix log issue DESeq2 rule
use sequential color scale in DESeq2 expression heatmap
change default conda prefix to new location

small fixes

---

snakePipes/shared/rules/RNA_mapping.snakefile
snakePipes/shared/rules/RNA_mapping_allelic.snakefile
snakePipes/shared/rules/envs/rna_seq.yaml
snakePipes/workflows/RNA-seq/RNA-seq
snakePipes/workflows/RNA-seq/defaults.yaml

Update STAR version and move --outBAMsortingBinsN to star_options

---

snakePipes/shared/tools/deeptools_cmds.snakefile

make PCA plot wider, set --plotWidth 10 as default

---

snakePipes/shared/rules/deepTools_ChIP_allelic.snakefile
snakePipes/workflows/ChIP-seq/ChIP-seq

closes #212 
fix issue with allelic rule

some other bugfixes

---

snakePipes/common_functions.py
snakePipes/workflows/DNA-mapping/internals.snakefile

Fix chip predict

---

docs/content/create_index.rst
docs/index.rst

This is an initial stab at documenting index creation, using hg38 as an example. Feel free to edit as you see fit.

Index documentation

---

bin/snakePipes
snakePipes/common_functions.py
snakePipes/parserCommon.py

Fix #252 and the --only option.

Fix --only and #252

---

snakePipes/workflows/RNA-seq/internals.snakefile

otherwise mode "deepTools_qc" is never called

fix RNA-seq: remove using lowercase for mode in internals.snakefile

---

docs/content/advanced_usage.rst
docs/content/setting_up.rst

I'm currently testing to ensure this renders correctly before merging.
@vivekbhr Please confirm that I've added the AWS documentation where it makes the most sense given your PR.

Document AWS and the premade indices

---

snakePipes/shared/rules/Salmon.snakefile
snakePipes/workflows/RNA-seq/cluster.yaml
snakePipes/workflows/scRNAseq/cluster.yaml

@vivekbhr This fixes some of the salmon issues you would have run into had you gotten your envs to behave.

Various salmon related fixes

---

docs/content/running_snakePipes.rst
snakePipes/common_functions.py

Copy organism yaml files into the output directory.

Implement #287

---

snakePipes/shared/rules/FASTQ.snakefile

ext for non-downsampled rules

---

docs/content/workflows/ATAC-seq.rst
snakePipes/common_functions.py
snakePipes/shared/rules/CSAW.snakefile
snakePipes/workflows/ATAC-seq/ATAC-seq
snakePipes/workflows/ATAC-seq/Snakefile
snakePipes/workflows/ATAC-seq/defaults.yaml
snakePipes/workflows/ChIP-seq/ChIP-seq
snakePipes/workflows/ChIP-seq/Snakefile
snakePipes/workflows/DNA-mapping/DNA-mapping
snakePipes/workflows/HiC/HiC
snakePipes/workflows/RNA-seq/RNA-seq
snakePipes/workflows/WGBS/WGBS
snakePipes/workflows/createIndices/Snakefile
snakePipes/workflows/createIndices/createIndices
snakePipes/workflows/scRNAseq/scRNAseq

The following need to be tested before merging:
Closes #294

Fix #294 and other issues that pop up in all of the pipelines.

---

snakePipes/shared/rscripts/WGBS_stats_report_template.Rmd
snakePipes/shared/rscripts/WGBSstats_functions.R
snakePipes/shared/rules/WGBS.snakefile
snakePipes/workflows/WGBS/cluster.yaml

- increased memory for rule prep_for_stats (WGBS)
- minor updates to rule dependency handling for WGBS stat reports

Ksikora minor fixe

---

docs/content/workflows/ATAC-seq.rst
snakePipes/shared/rscripts/scRNAseq_select_threshold_cluster_monocle.R

* added info to ATACseq docs
* updated seurat object is now saved in scRNAseq workflow

Minor additions

---

snakePipes/shared/rules/hicexplorer.snakefile

Added danglingSequence and restrictionSequence to hicBuildMatrix in case of bs

Added danglingSequence and restrictionSequence to hicBuildMatrix 

---

docs/content/News.rst

updated News.rst with information about fastqc reports

updated news.rst

---

snakePipes/common_functions.py
snakePipes/shared/defaults.yaml
snakePipes/shared/rscripts/CSAW.R
snakePipes/shared/rscripts/DESeq2.R
snakePipes/shared/rscripts/DE_functions.R
snakePipes/shared/rules/envs/atac_seq.yaml
snakePipes/shared/rules/masked_genomeIndex.snakefile
snakePipes/workflows/RNA-seq/cluster.yaml

skip empty lines in check_replicates

allelic_RNA_seq

---

.ci_stuff/test_dag.sh
snakePipes/shared/rules/multiQC.snakefile
snakePipes/workflows/RNA-seq/cluster.yaml

* increase memory for Salmon post proc steps
* MultiQC 1.7 can handle more deepTools output, use for DAN-mapping and RNA-seq,
* include Salmon dirs for alignment-free RNA-seq

improve RNAseq

---

docs/content/News.rst
snakePipes/shared/cluster.yaml
snakePipes/shared/rules/masked_genomeIndex.snakefile
snakePipes/workflows/DNA-mapping/Snakefile
snakePipes/workflows/RNA-seq/cluster.yaml

updated memory for allele specific rules

Allele specific dna mapping

---

snakePipes/common_functions.py
snakePipes/shared/rules/umi_tools.snakefile

Implement #453

---

docs/content/workflows/DNA-mapping.rst
docs/content/workflows/HiC.rst
docs/content/workflows/RNA-seq.rst
snakePipes/workflows/DNA-mapping/DNA-mapping
snakePipes/workflows/HiC/HiC
snakePipes/workflows/RNA-seq/RNA-seq
snakePipes/workflows/RNA-seq/Snakefile

fixed the bug mentioned in #519. 
Modified the documentation by adding umi parameters to the default yamls.

litlle bug fix and chagnes in the doc for umi

---

snakePipes/common_functions.py
snakePipes/shared/defaults.yaml
snakePipes/workflows/ATAC-seq/Snakefile
snakePipes/workflows/ChIP-seq/Snakefile
snakePipes/workflows/DNA-mapping/Snakefile
snakePipes/workflows/HiC/Snakefile
snakePipes/workflows/HiC/defaults.yaml
snakePipes/workflows/HiC/internals.snakefile
snakePipes/workflows/WGBS/Snakefile
snakePipes/workflows/createIndices/Snakefile
snakePipes/workflows/mRNA-seq/Snakefile
snakePipes/workflows/noncoding-RNA-seq/Snakefile
snakePipes/workflows/preprocessing/Snakefile
snakePipes/workflows/scRNAseq/Snakefile

Added a function which writes the tools of the shared env and pipeline specific env along with their versions on a text file. This is by default `True` but can be set to `False`  in `shared default.yaml` to avoid writing them.

Tools version

---

snakePipes/workflows/preprocessing/preprocessing

Implement automatic sample sheet generation for standard Illumina stuff as mentioned in #546

Implement #546

---

snakePipes/shared/rules/ATAC.snakefile

I fixed a typo which was reported in #622

fixed a typo in alignmentSieve rule

---

snakePipes/common_functions.py
snakePipes/workflows/DNA-mapping/internals.snakefile

fix for #654

---

.ci_stuff/test_dag.sh
snakePipes/shared/rules/envs/hic.yaml
snakePipes/shared/rules/hicexplorer.snakefile

hicexplorer has been updated to 3.5

HiCExplorer3.5

---

snakePipes/shared/rules/envs/hic.yaml

hic version has been bumped up to 3.6 #718

hic version has been bumped up to 3.6

---

snakePipes/shared/rules/rMats.multipleComp.snakefile
snakePipes/shared/rules/rMats.singleComp.snakefile
snakePipes/shared/rules/rMats.snakefile

rMats force int when trimmed reads

---

azure-pipelines.yml
docs/content/News.rst

news update for the release 2.5.0

News update

---

conda-recipe/meta.yaml

updated conda_recipe

---

.ci_stuff/test_dag.sh
snakePipes/shared/rules/envs/shared.yaml
snakePipes/workflows/HiC/Snakefile

updated multiqc version to be able to make qc reports for hic pipeline too.

multiqc version has been updated

---

snakePipes/shared/rules/ChIP_peak_calling.snakefile
snakePipes/shared/rules/ChIP_peak_calling_spikein.snakefile
snakePipes/workflows/ChIP-seq/internals.snakefile

macs2 bug if spikein but not cutnx #777

fixed macs2 bug , if spike in but not cutnx

---

snakePipes/shared/rules/envs/shared.yaml
snakePipes/shared/rules/multiQC.snakefile

#781 
- Added bamPEFragmentSize to multiqc
- Updated the deeptols version

fixed the issue #781

---

.azure-pipelines/setup.yml
azure-pipelines.yml
docs/conf.py
docs/content/setting_up.rst

Hopefully, this will solve actual and future issues.

---

README.rst
bin/snakePipes
conda-recipe/meta.yaml
docs/content/setting_up.rst
docs/index.rst

Mirroring what we already changed on setting_up.rst

---

snakePipes/shared/rules/DESeq2.singleComp.snakefile

This is the real change, modularization_ronald was somehow broken,

Adjusted DESeq2.singleComp.snakefile for modulariz

---

conda-recipe/meta.yaml
requirements.txt

cfr https://github.com/snakemake/snakemake/issues/1891

Tabulate cap

---

docs/content/News.rst

updated the news.rst file

---

.ci_stuff/test_dag.sh
snakePipes/workflows/mRNA-seq/Snakefile
snakePipes/workflows/mRNA-seq/defaults.yaml
snakePipes/workflows/mRNA-seq/mRNA-seq

- moved the `--three-prime-seq` flag to mRNA seq modes

3primeseq ks

---

snakePipes/shared/rscripts/WGBS_QC_report_template.Rmd

Fix pca wgbs

---

.ci_stuff/test_dag.sh
.github/workflows/linux.yml
.github/workflows/osx.yml
bin/snakePipes
docs/content/News.rst
snakePipes/common_functions.py
snakePipes/shared/rscripts/CSAW.R
snakePipes/shared/rscripts/nearestGene.R
snakePipes/shared/rules/CSAW.multiComp.snakefile
snakePipes/shared/rules/CSAW.singleComp.snakefile
snakePipes/shared/rules/ChIP_peak_calling.snakefile
snakePipes/shared/rules/ChIP_peak_calling_spikein.snakefile
snakePipes/workflows/ATAC-seq/ATAC-seq
snakePipes/workflows/ATAC-seq/defaults.yaml
snakePipes/workflows/ATAC-seq/internals.snakefile
snakePipes/workflows/ChIP-seq/ChIP-seq
snakePipes/workflows/ChIP-seq/Snakefile
snakePipes/workflows/ChIP-seq/defaults.yaml
snakePipes/workflows/ChIP-seq/internals.snakefile
tests/test_jobcounts.py

* added SEACR peak qc
* added external bed functionality for differential binding in ChIP-seq and ATAC-seq workflows
* fixed copyfile command for sampleSheet 
* removed deprecated `--force` argument from mamba commands
* fixes #998 
* fixes #997 
* fixes #996

Chipseq ks

---

.ci_stuff/test_dag.sh
.github/workflows/osx.yml
snakePipes/common_functions.py
snakePipes/shared/rules/ChIP_peak_calling.snakefile
snakePipes/shared/rules/ChIP_peak_calling_spikein.snakefile
snakePipes/shared/rules/Salmon.snakefile
snakePipes/shared/rules/Salmon_allelic.snakefile
snakePipes/shared/rules/createIndices.snakefile
snakePipes/shared/rules/envs/rna_seq.yaml
snakePipes/shared/rules/envs/salmon.yaml
snakePipes/shared/rules/scRNAseq_Alevin.snakefile
snakePipes/workflows/ChIP-seq/Snakefile
snakePipes/workflows/ChIP-seq/cluster.yaml
tests/test_jobcounts.py

Extentions2 ks

---

conda-recipe/build.sh
conda-recipe/meta.yaml

conda build working locally
