maxplanck-ie/snakepipes

- workflows/ChIP-seq/ChIP-seq
Fixed problem that ChIP-seq workflow runs only in single-end mode, regardless of user config file.
> ChIP-seq workflow patched

- shared/rules/hicexplorer.snakefile
The snakepipes were crashing because `{params.idx}` in `rule map_fastq_single_end:` were not properly named.
> fixed a typo for mapping rule of hicexplorer.snakefile

- snakePipes/shared/rscripts/WGBSpipe.interval_stats.limma.R
- snakePipes/shared/rscripts/WGBSpipe.metilene_stats.limma.R
- snakePipes/shared/rscripts/WGBSpipe.singleCpGstats.limma.R
- snakePipes/shared/rules/WGBS.snakefile
- snakePipes/workflows/WGBS/cluster.yaml
Renaming of samples via PlottingID was disabled. To be re-implemented at some point in the future.
Memory usage for aggregate statistics rules was increased.
One output path was corrected for aggregate stats rule.
> R stats-related fixes

- snakePipes/shared/rules/envs/wgbs.yaml
It fixes an issue with rmarkdown crashing during QC reports rules of the WGBS pipeline. Before this patch, rmarkdown 0.9.3 is installed by default, which doesn't take into account snakemake's knit_root_dir parameter passed to rmarkdown::render.
This patch should fix it (I also encountered errors about htmltools and yaml packages that are ̀installed by an R version with different internals; it needs to be reinstalled for use with this R version`, I'm not sure this patch fixes that).
> Fix for snakemake's knit_root_dir parameter passed to rmarkdown::render

- .ci_stuff/test_dag.sh
- snakePipes/shared/rules/createIndices.snakefile
This will kill createIndices if there is not at least 1 chromosome name shared between the fasta and GTF file.
> Implement #489, check for chromosome name consistency when creating indices

- .ci_stuff/test_dag.sh
- docs/content/workflows/ATAC-seq.rst
- docs/content/workflows/ChIP-seq.rst
- snakePipes/common_functions.py
- snakePipes/shared/rscripts/CSAW.R
- snakePipes/shared/rules/ATAC.snakefile
- snakePipes/shared/rules/CSAW.snakefile
- snakePipes/shared/rules/ChIP_peak_calling.snakefile
- snakePipes/shared/rules/envs/atac_seq.yaml
- snakePipes/workflows/ATAC-seq/ATAC-seq
- snakePipes/workflows/ATAC-seq/Snakefile
- snakePipes/workflows/ATAC-seq/defaults.yaml
- snakePipes/workflows/ATAC-seq/internals.snakefile
- snakePipes/workflows/ChIP-seq/ChIP-seq
- snakePipes/workflows/ChIP-seq/Snakefile
- snakePipes/workflows/ChIP-seq/defaults.yaml
- snakePipes/workflows/ChIP-seq/internals.snakefile
- snakePipes/workflows/createIndices/Snakefile
This adds Genrich as a peak caller to ChIP-seq and ATAC-seq, which is configurable with the `--peakCaller` option. HMMRATAC is additionally added as an option to the ATAC-seq pipeline.
HMMRATAC is quite slow whereas Genrich is quicker than MACS2. Genrich generally seems to produce better results on our test data than MACS2 and HMMRATAC, but this may be dataset dependent. Genrich is using replicates in ATAC-seq, but not (yet at least) ChIP-seq. CSAW will look for input from the appropriate peak caller, which has been tested in the ATAC pipeline.
Note that the Genrich command is written to essentially require paired-end data, so that needs to be documented.
> Expand ATAC, implement #553

- snakePipes/shared/rules/preprocessing.snakefile
This was a small typo that broke the rule.
> Fix issue 569

- snakePipes/shared/rules/deepTools_qc.snakefile
Because single-end experiments requires this option to be set, the argument only had one hyphen instead of two.
> Fixed --fragmentLength argument in computeGCBias rule

- docs/content/setting_up.rst
Updated zenodo links to point to premade indices including STAR index compatible with 2.7.4a and later versions.
> zenodo links for indices

- snakePipes/shared/rscripts/DESeq2Report.Rmd
Closes #759
In case there is only one single DEG gene, the variable heatmap_data is NOT being created, however later used because in line 382, the check was for >0 instead for >1. This then leads to the well understandable error that the object heatmap_data does not exist.
I changed all related checks to >0, because I don't see a reason why >1 would make sense, but of course both are possible. Just not both at the same time as is the case for the moment.
> Always check for >0 rows with regard to using heatmap_data

- snakePipes/shared/rules/DESeq2.singleComp.snakefile
in DE single comp I saw that allelic-mapping in mode was not defined as a string
> error correction

- .ci_stuff/test_dag.sh
- .github/snakePipesEnvCI.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- tests/test_jobcounts.py
Some proposed changes to the CI tests.
-  snakemake 7.18.2 capped in envCI yaml (previously snakemake 6.x was pulled in, which != version in the latest releases)
- include graphviz in envCI yaml ( 'dot' is not available on gh action runners, not sure why this doesn't cause issues in test_dag.sh  )
- strict channel priorities w/ new setup-micromamba (@adRn-s )
and the initiation of pytests for testing the workflows 
- tests exitcodes
- tests number of jobs (rather then linecount #901), hopefully this will be more versatile across snakemake versions
- test data is created as a fixture, omitting the need for the files in .ci_stuff
> CICD updates

- snakePipes/common_functions.py
see: https://readthedocs.org/projects/snakepipes/builds/21581371/
```
File "../snakePipes/workflows/ATAC-seq/ATAC-seq", line 14, in <module>
import snakePipes.common_functions as cf
File "<fstring>", line 1
(err=)
^
SyntaxError: invalid syntax
```
> Fix docs build

- snakePipes/shared/cluster.yaml
The default (1G/thread) doesn't cut it for samples with 40 - 70M PE reads in allelic mode, causing cgroup failures or spillage to disk.
up memory defaults for sambamba_markdup, bamsort_allelic & snp_split
> memory resources allelic mode

- tests/test_jobcounts.py
Should take care of the pytest issues with SEACR runs, and all the ones where the jobcount is also aberrant.
ruamel is not an explicit dependency yet. Testing wether this should be the case.
> ruamel - fix ChIPtests

- snakePipes/shared/rscripts/WGBS_QC_report_template.Rmd
- snakePipes/shared/rules/WGBS.snakefile
- snakePipes/shared/rules/envs/hic.yaml
- snakePipes/shared/rules/envs/shared.yaml
multiqc and py 3.7 are not compatible anymore and needs a more recent python version. This is an attempt to (drastically) boost the shared_env versions. Currently still testing all the workflows for any hiccups
> bugfix 2.8.0

- .github/conda_ci.yml
- .github/snakePipesEnvCI.yml
- .github/workflows/conda-build.yml
- .github/workflows/linux.yml
- .github/workflows/osx.yml
- .github/workflows/pytest.yml
simplify CI tests, include pip install for py versions 3.11 / 3.12 & opt deps
> Pairtools ci

- snakePipes/shared/rules/SNPsplit.snakefile
- snakePipes/shared/rules/createIndices.snakefile
- snakePipes/shared/rules/three_prime_seq.snakefile
- snakePipes/shared/rules/trimming.snakefile
- snakePipes/snakePipes.py
- comment out temp bam files SNPsplit rule, as they are not (or no longer?) generated.
- regex fixes in createIndices / threeprimeseq
- purge some todo / bloated comments in threeprimeseq 
- default trimming is done for illumina stranded adapter instead of TruSeq
- basic profile checks upon invocation of createEnvs
- createEnvs counter fixed if --only is set
closes #1031, #1029
> Pairtools finaltweaks

- snakePipes/snakePipes.py
- snakePipes/workflows/DNAmapping/Snakefile
- snakePipes/workflows/mRNAseq/Snakefile
> Fix 1049 and 1009

- snakePipes/shared/rules/split_bam_ops_ChIP_spikein.snakefile
Fixes an internally reported bug, where {log} out wasn't omitted from the shell command (deprecated with profile use).
> drop log as omitted by profile

- .github/workflows/linux.yml
- .github/workflows/osx.yml
- conda-recipe/meta.yaml
- docs/conf.py
- docs/content/News.rst
- docs/content/workflows/makePairs.rst
- pyproject.toml
- snakePipes/parserCommon.py
- snakePipes/shared/defaults.yaml
- snakePipes/shared/rules/envs/makePairs.yaml
- snakePipes/shared/rules/pairtools.snakefile
- snakePipes/shared/rules/pairtools_allelic.snakefile
- snakePipes/snakePipes.py
- snakePipes/workflows/makePairs/Snakefile
- snakePipes/workflows/makePairs/defaults.yaml
- snakePipes/workflows/makePairs/internals.snakefile
- v3.0.1
- python 3.13 installation test
- minor docs changes for makePairs
- docs conf.py fix for latest sphinx
- bulk makePairs mode up to mcool generation, including mqcs
- previous allelic makePairs mode moved to 'makePairs_allelic' rule file.
- conda-recipe has an non-inclusive upper bound for 3.13, at least until conda build works w 3.13
- Increased verbosity in createEnvs (prints actual conda create command now)
- included some news (for 3.0.0 as well)
Closes #1026
> Pairtools merge

- .ci_stuff/test_dag.sh
- docs/content/News.rst
- docs/content/workflows/mRNAseq.rst
- pyproject.toml
- snakePipes/common_functions.py
- snakePipes/shared/defaults.yaml
- snakePipes/shared/rules/WGBS.snakefile
- snakePipes/shared/rules/createIndices.snakefile
- snakePipes/shared/rules/envs/picard.yaml
- snakePipes/shared/rules/multiQC.snakefile
- snakePipes/shared/rules/scRNAseq_STARsolo.snakefile
- snakePipes/shared/rules/whatshap.snakefile
- snakePipes/workflows/WGBS/Snakefile
- snakePipes/workflows/mRNAseq/internals.snakefile
- snakePipes/workflows/scRNAseq/Snakefile
- tests/test_jobcounts.py
- fixes #1085 
- fixes #1083 
- fixes #1082 
- fixes #1063 
- fixes #1058 
- fixes #1024 
- fixes minor issues with mRNAseq allelic-whatshap mode
> Issue fixes
